# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: "protoc-gen-nats"
before:
  hooks:
    - go mod tidy
    - make clean
builds:
  - id: "proto-gen-nats"
    main: ./cmd/protoc-gen-nats/
    binary: "protoc-gen-nats"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - '-s'
      - '-w'
      - '-X main.version={{ .Version }}'
      - '-extldflags "-static"'
archives:
  - id: "proto-gen-nats"
    builds:
      - "proto-gen-nats"
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "darwin" }}osx
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

# vim: set ts=2 sw=2 tw=0 fo=cnqoj
