// Code generated by protoc-gen-nats v0.0.0, DO NOT EDIT.
// source: transfers.nats.go

/*
Package protocol is a generated proto-nats stub package.
This code was generated with github.com/faabiosr/proto-nats/protoc-gen-nats v0.0.0.

It is generated from these files:
	transfers.nats.go
*/
package protocol

import (
	"context"
	"errors"
	"time"

	pn "github.com/faabiosr/proto-nats/proto"
	"github.com/golang/protobuf/ptypes"
	nats "github.com/nats-io/nats.go"
)

const (
	TransferVerifySubject  = "transfer.verify"
	TransferExecuteSubject = "transfer.execute"
)

// Transfer Interface
type Transfer interface {
	Verify(context.Context, *TransferRequest) (*TransferResponse, error)
	Execute(context.Context, *TransferRequest) (*TransferResponse, error)
}

// Transfer Encoded Subscriber
type transferEncodedSubscriber struct {
	enc       *nats.EncodedConn
	queueName string
	svc       Transfer
	subs      []*nats.Subscription
}

// NewTransferEncodedSubscriber creates a transferEncodedSubscriber that implements the QueueSubscriber.
func NewTransferEncodedSubscriber(enc *nats.EncodedConn, queueName string, svc Transfer) pn.QueueSubscriber {
	return &transferEncodedSubscriber{enc, queueName, svc, []*nats.Subscription{}}
}

// Subscribe will register the services in encoded queue broker.
func (s *transferEncodedSubscriber) Subscribe() error {
	if err := s.register(s.enc.QueueSubscribe(TransferVerifySubject, s.queueName, s.verify)); err != nil {
		return err
	}

	if err := s.register(s.enc.QueueSubscribe(TransferExecuteSubject, s.queueName, s.execute)); err != nil {
		return err
	}

	return nil
}

// Unsubscribe will unregister the services from the encoded queue broker.
func (s *transferEncodedSubscriber) Unsubscribe() error {
	if len(s.subs) == 0 {
		return nil
	}

	for _, sub := range s.subs {
		if err := sub.Unsubscribe(); err != nil {
			return err
		}
	}

	return nil
}

func (s *transferEncodedSubscriber) register(sub *nats.Subscription, err error) error {
	if err != nil {
		return err
	}

	s.subs = append(s.subs, sub)

	return nil
}

// ==================

func (s *transferEncodedSubscriber) verify(subject, reply string, req *TransferRequest) {
	res, err := s.svc.Verify(context.Background(), req)

	if len(reply) == 0 {
		return
	}

	if err != nil {
		s.enc.Publish(reply, &pn.EncodedMessage{Error: err.Error()})
		return
	}

	msg := &pn.EncodedMessage{}
	msg.Body, err = ptypes.MarshalAny(res)

	if err != nil {
		msg.Error = err.Error()
	}

	s.enc.Publish(reply, msg)
}
func (s *transferEncodedSubscriber) execute(subject, reply string, req *TransferRequest) {
	res, err := s.svc.Execute(context.Background(), req)

	if len(reply) == 0 {
		return
	}

	if err != nil {
		s.enc.Publish(reply, &pn.EncodedMessage{Error: err.Error()})
		return
	}

	msg := &pn.EncodedMessage{}
	msg.Body, err = ptypes.MarshalAny(res)

	if err != nil {
		msg.Error = err.Error()
	}

	s.enc.Publish(reply, msg)
}

// =======================
// Transfer Encoded Client
// =======================
type transferEncodedClient struct {
	enc     *nats.EncodedConn
	timeout time.Duration
}

// NewTransferEncodedClient creates a transferEncodedClient thtat implements the Transfer.
func NewTransferEncodedClient(enc *nats.EncodedConn, timeout time.Duration) Transfer {
	return &transferEncodedClient{enc, timeout}
}

func (c *transferEncodedClient) Verify(ctx context.Context, req *TransferRequest) (*TransferResponse, error) {
	var msg pn.EncodedMessage

	if err := c.enc.Request(TransferVerifySubject, req, &msg, c.timeout); err != nil {
		return nil, err
	}

	if err := msg.GetError(); len(err) != 0 {
		return nil, errors.New(err)
	}

	res := &TransferResponse{}

	if err := ptypes.UnmarshalAny(msg.GetBody(), res); err != nil {
		return nil, err
	}

	return res, nil
}

func (c *transferEncodedClient) Execute(ctx context.Context, req *TransferRequest) (*TransferResponse, error) {
	var msg pn.EncodedMessage

	if err := c.enc.Request(TransferExecuteSubject, req, &msg, c.timeout); err != nil {
		return nil, err
	}

	if err := msg.GetError(); len(err) != 0 {
		return nil, errors.New(err)
	}

	res := &TransferResponse{}

	if err := ptypes.UnmarshalAny(msg.GetBody(), res); err != nil {
		return nil, err
	}

	return res, nil
}
