// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EncodedMessage struct {
	Body                 *any.Any `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncodedMessage) Reset()         { *m = EncodedMessage{} }
func (m *EncodedMessage) String() string { return proto.CompactTextString(m) }
func (*EncodedMessage) ProtoMessage()    {}
func (*EncodedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *EncodedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncodedMessage.Unmarshal(m, b)
}
func (m *EncodedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncodedMessage.Marshal(b, m, deterministic)
}
func (m *EncodedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncodedMessage.Merge(m, src)
}
func (m *EncodedMessage) XXX_Size() int {
	return xxx_messageInfo_EncodedMessage.Size(m)
}
func (m *EncodedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EncodedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EncodedMessage proto.InternalMessageInfo

func (m *EncodedMessage) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *EncodedMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*EncodedMessage)(nil), "proto_nats.EncodedMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x53, 0xf1, 0x79, 0x89,
	0x25, 0xc5, 0x52, 0x92, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0xa1, 0xa4, 0xd2, 0x34,
	0xfd, 0xc4, 0xbc, 0x4a, 0x88, 0x32, 0xa5, 0x00, 0x2e, 0x3e, 0xd7, 0xbc, 0xe4, 0xfc, 0x94, 0xd4,
	0x14, 0x5f, 0x88, 0x76, 0x21, 0x0d, 0x2e, 0x96, 0xa4, 0xfc, 0x94, 0x4a, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0x6e, 0x23, 0x11, 0x3d, 0x88, 0x5e, 0x3d, 0x98, 0x5e, 0x3d, 0xc7, 0xbc, 0xca, 0x20, 0xb0,
	0x0a, 0x21, 0x11, 0x2e, 0xd6, 0xd4, 0xa2, 0xa2, 0xfc, 0x22, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x08, 0xc7, 0x89, 0x3d, 0x8a, 0x15, 0xa2, 0x96, 0x0d, 0x4c, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xac, 0x7a, 0x1d, 0x07, 0x99, 0x00, 0x00, 0x00,
}
