name: test

on:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.13'

      - name: install golanci-linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

      - name: install app dependencies
        run: make configure

      - name: build app
        run: make build

      - name: run unit tests
        run: make test

      - name: run linter
        run: make lint

      - name: upload code coverage
        uses: codecov/codecov-action@v3
        if: contains(github.ref, 'master')
        with:
          file: ./cover.out
